from pyglet.window import Window

__all__ = ["MouseCursors"]

class MouseCursors:
    DEFAULT = Window.CURSOR_DEFAULT
    CROSSHAIR = Window.CURSOR_CROSSHAIR
    HAND = Window.CURSOR_HAND
    HELP = Window.CURSOR_HELP
    NO = Window.CURSOR_NO
    SIZE = Window.CURSOR_SIZE
    SIZE_DOWN = Window.CURSOR_SIZE_DOWN
    SIZE_DOWN_LEFT = Window.CURSOR_SIZE_DOWN_LEFT
    SIZE_DOWN_RIGHT = Window.CURSOR_SIZE_DOWN_RIGHT
    SIZE_LEFT = Window.CURSOR_SIZE_LEFT
    SIZE_LEFT_RIGHT = Window.CURSOR_SIZE_LEFT_RIGHT
    SIZE_RIGHT = Window.CURSOR_SIZE_RIGHT
    SIZE_UP = Window.CURSOR_SIZE_UP
    SIZE_UP_DOWN = Window.CURSOR_SIZE_UP_DOWN
    SIZE_UP_LEFT = Window.CURSOR_SIZE_UP_LEFT
    SIZE_UP_RIGHT = Window.CURSOR_SIZE_UP_RIGHT
    TEXT = Window.CURSOR_TEXT
    WAIT = Window.CURSOR_WAIT
    WAIT_ARROW = Window.CURSOR_WAIT_ARROW